### ISSUE TITLE
ENHANCEMENT: Add golint as workflow job

### ISSUE THREAD

**Issue by Cian911** [Cian911/gomerge#23]
In order to improve the code quality of `gomerge`, we should implement a number of automated code quality checks.

This issue related specifically to `golint`. This should be implemented as a job in the https://github.com/Cian911/gomerge/blob/master/.github/workflows/test.yml workflow file. This should run before the main test suite and should fail the entire workflow if a change fails.

**Comment by CutestNekoAqua** [comment]
I'd like to do this ^^

**Comment by Cian911** [comment]
Done in https://github.com/Cian911/gomerge/pull/59
