### ISSUE TITLE
Add squash & merge option

### ISSUE THREAD

**Issue by RhinosF1** [Cian911/gomerge#25]
Hello,

Is there a way to squash and merge PRs via this tool?

We prefer to squash when committing for our org but this tool saved me a stack of time.

**Comment by RhinosF1** [comment]
Thanks @Cian911!

It's a great tool and made my work so much easier.

**Comment by Cian911** [comment]
Thanks again @RhinosF1 ! Don't forget to give us a star if you haven't already, it really helps :)
