### ISSUE TITLE
feat: ignore errors flag

### ISSUE THREAD

**Issue by Bluscream** [Cian911/gomerge#40]
i would like for the script to continue even if one of the PRs is unmergable

**Comment by Cian911** [comment]
I will take a look - thanks!

**Comment by Bluscream** [comment]
That would help me a lot :)

**Comment by Cian911** [comment]
Hi @Bluscream,

I added a new optional flag `skip` which will continue merging/approving any subsequent PRs should one or more be un-mergable. The change will be in the next realese which might be in the next week or so after I add a few other things, but you can build from source in the meantime if you'd like to try it out :) 

Hope this works for you!

**Comment by Bluscream** [comment]
Thanks a lot! Make sure to close the issue when the release rolls out so i don't forget testing it :D
