### ISSUE TITLE
feat: ability to close unmergable PRs

### ISSUE THREAD

**Issue by Bluscream** [Cian911/gomerge#41]

**Comment by Bluscream** [comment]
No, thank **you** for taking a look! On a more serious note, sorry for not providing a proper description, i was in a hurry when i dropped that. Apparently it was self-explanatory enough though 😅

**Comment by Cian911** [comment]
This will also form part of the next release `v3.0.0` shortly

**Comment by Cian911** [comment]
And `v3.0.0` is released! I hope this helps you @Bluscream, please give us a star if you get a chance, as it helps me out. Thanks again for the requests!

**Comment by Bluscream** [comment]
Thanks a lot!
