### ISSUE TITLE
FEATURE: Windows OS support

### ISSUE THREAD

**Issue by scowalt** [Cian911/gomerge#64]
I was planning on using this tool to manage some of my repos, but I'm on Windows 🙂.

There's no prebuilt binaries. For now, I'll attempt to build from source. I assume that this will work? I haven't dug deep enough to see if anything is unix-specific

**Comment by scowalt** [comment]
Confirmed that this works on Windows from `gomerge.exe` built using `go build`

**Comment by scowalt** [comment]
I've done a tiny bit of research into this. The pattern I've seen in other repositories appears to be:
- Have separate `.goreleaser.yml` configurations for each platform
- In `release.yml`, call `goreleaser-action` once for each platform

([source](https://github.com/search?q=goreleaser+windows+extension%3Ayml+path%3A.github%2Fworkflows&type=Code&ref=advsearch&l=&l=))

I'm not sure how appropriate this pattern is or how big of a lift it is. (I know nothing about the larger go ecosystem!)

**Comment by Cian911** [comment]
Hey @scowalt ! Many thanks for taking the time in interest in `gomerge`. It's always great to see new people come along to use it.

I've gone ahead and added support for windows in the linked PR attached to this. I've also created a new release candidate version if you'd like to download and test out the binary in the system most appropriate to you [here](https://github.com/Cian911/gomerge/releases/tag/3.2.0-rc).

If you can let me know how you get on and everything is working well I'll bump the release. :) 

Thanks again!

**Comment by Cian911** [comment]
Awesome @scowalt I've gone ahead and bumped the version so this `3.2.0` is now the latest release. I'll go ahead and close this issue now - but If I could ask if you might give `gomerge` a star while you're here (if you haven't already!) it really helps me out. Thank you!
