### ISSUE TITLE
FEATURE: Ability to add a comment when approving a PR

### ISSUE THREAD

**Issue by emmaLP** [Cian911/gomerge#80]
As a developer, I want to be able to leave a comment on a PR when approving.

Use case: when approving dependabot PRs, to comment with `@dependabot merge` so when the PRs meets the merge requirement then dependabot will auto merge the PR

**Comment by Cian911** [comment]
Thanks for the requests. I will see what I can do about this and https://github.com/Cian911/gomerge/issues/79

**Comment by Cian911** [comment]
@emmaLP This is released now https://github.com/Cian911/gomerge/releases/tag/3.3.0
