### ISSUE TITLE
Bug?: error message when approving PR, but PR gets approved

### ISSUE THREAD

**Issue by braun1928** [Cian911/gomerge#86]
Trying this tool to assist with the huge amount of dependabot PRs, and I saw an odd behaviour with approving PRs. Every time I get this output:
```
2023/10/17 15:26:18 Could not approve pull request, did you try to approve your on pull request? Skipping: <nil>
PR #43: APPROVED
```
The PR gets approved as shown in the second line, and there is no error in the http request (checked with `mitmproxy`, returns 200 as expected, the payload looks okay).

**Comment by Cian911** [comment]
Thanks for the report @braun1928.

Did you have the `skip` flag enabled when running `gomerge`?

I do see a small bug [here](https://github.com/Cian911/gomerge/blob/65bd6d834e753b050434d32ba8ef59eaa0cad523/pkg/gitclient/client.go#L50), I'm using the `err` value (which will be nil in this case) when I should be using `skip`. I will fix that.

**Comment by braun1928** [comment]
I have not, just -a and -r. I saw that block as well, seems to be an easy fix, but didn't have the time to fork and try it myself

**Comment by Cian911** [comment]
Should be fixed now with latest release https://github.com/Cian911/gomerge/releases/tag/3.3.0

Thanks again for the report, and thanks for using gomerge! Please do give us a star if you can :pray:
